# There is a scheduled trigger defined in Azure DevOps since this is currently impossible in YAML
# Every night at 00:00

trigger:
  branches:
    exclude: ['*']
  tags:
    exclude: ['*']

pr: none

pool:
  name: Hosted VS2017
steps:
- task: AzureCLI@1
  displayName: 'Execute retention policy'
  inputs:
    azureSubscription: '$(azureSubscription)'
    scriptLocation: inlineScript
    inlineScript: 'PowerShell -Command "$(System.DefaultWorkingDirectory)/build.ps1 ExecuteRetentionPolicy -GitHubRepositoryName $(gitHubRepositoryName) -ACRName $(acrName) -DryRun $(dryRun)"'
