version: '2.4'

services:
  sitecore:
    volumes:
      - .\sitecore\sxa:C:\sxa
      - ..\files:C:\files-mount
      - .\license:C:\license  
    environment:
      PSE_PACKAGE: ${PSE_PACKAGE}
      SXA_PACKAGE: ${SXA_PACKAGE}
