# escape=`

# Stage 0: prepare files
FROM microsoft/aspnet:4.7.1-windowsservercore-1709 AS prepare

ARG CONFIG_PACKAGE

SHELL ["powershell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop';"]

ADD files/$CONFIG_PACKAGE /Files/

RUN Expand-Archive -Path /Files/$Env:CONFIG_PACKAGE -DestinationPath /Files/Config 


# Stage 1: create actual image
FROM microsoft/aspnet:4.7.1-windowsservercore-1709

ARG SQL_SA_PASSWORD
ARG SQL_DB_PREFIX
ARG SQL_SERVER="mssql"
ARG SITE_NAME="xconnect"
ARG SOLR_CORE_PREFIX="xp0"
ARG SOLR_PORT="8983"
ARG XCONNECT_PACKAGE

SHELL ["powershell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop';"] 

COPY files/license.xml /Files/
COPY files/$XCONNECT_PACKAGE /Files/
COPY files/*.pfx /Files/
COPY --from=prepare /Files/Config /Files/Config/
ADD scripts /Scripts

ENV SOLR_CERT_PATH "c:\\Files\\solr.pfx"
ENV XCONNECT_CERT_PATH "C:\\Files\\xConnect.pfx"

# Trust Self signed certificates
RUN /Scripts/Import-Certificate.ps1 -certificateFile $Env:SOLR_CERT_PATH -secret 'secret' -storeName 'Root' -storeLocation 'LocalMachine'
RUN /Scripts/Import-Certificate.ps1 -certificateFile $Env:XCONNECT_CERT_PATH -secret 'secret' -storeName 'Root' -storeLocation 'LocalMachine'

# Import XConnect certificate
RUN /Scripts/Import-Certificate.ps1 -certificateFile $Env:XCONNECT_CERT_PATH -secret 'secret' -storeName 'My' -storeLocation 'LocalMachine'

RUN /Scripts/Install-SIF.ps1

# Install WebDeploy
ENV WEBDEPLOY_MSI="webdeploy.msi"
ADD http://download.microsoft.com/download/0/1/D/01DC28EA-638C-4A22-A57B-4CEF97755C6C/WebDeploy_amd64_en-US.msi ${WEBDEPLOY_MSI}
RUN Start-Process msiexec.exe -ArgumentList '/i', $Env:WEBDEPLOY_MSI, '/quiet', '/norestart' -NoNewWindow -Wait

# Install IIS URL Rewrite
ENV URLREWRITE_MSI="urlrewrite.msi"
ADD http://download.microsoft.com/download/D/D/E/DDE57C26-C62C-4C59-A1BB-31D58B36ADA2/rewrite_amd64_en-US.msi ${URLREWRITE_MSI}
RUN Start-Process msiexec.exe -ArgumentList '/i', $Env:URLREWRITE_MSI, '/quiet', '/norestart' -NoNewWindow -Wait

RUN Remove-Website -Name 'Default Web Site'

ENV SIF_CONFIG="c:\\Files\\Config\\xconnect-xp0.json"

RUN $config = Get-Content $Env:SIF_CONFIG | Where-Object { $_ -notmatch '^\s*\/\/'} | Out-String | ConvertFrom-Json; `
    $config.Tasks.InstallWDP.Params.Arguments | Add-Member -Name 'Skip' -Value @(@{'ObjectName' = 'dbDacFx'}, @{'ObjectName' = 'dbFullSql'}) -MemberType NoteProperty; `
    ConvertTo-Json $config -Depth 50 | Set-Content -Path $Env:SIF_CONFIG

RUN Install-SitecoreConfiguration -Path "c:\\Files\\Config\\xconnect-createcert.json" `
    -CertificateName "xconnect_client"

RUN $solrUrl = 'https://solr:{0}/solr' -f $Env:SOLR_PORT; `
    Install-SitecoreConfiguration -Path $Env:SIF_CONFIG `
    -Package c:/Files/$Env:XCONNECT_PACKAGE `
    -LicenseFile "c:\\Files\\license.xml" `
    -Sitename $Env:SITE_NAME `
    -XConnectCert "xConnect.client" `
    -SqlDbPrefix $Env:SQL_DB_PREFIX `
    -SqlServer $Env:SQL_SERVER `
    -SqlAdminUser "sa" `
    -SqlAdminPassword $Env:SQL_SA_PASSWORD `
    -SqlCollectionUser "sa" `
    -SqlCollectionPassword $Env:SQL_SA_PASSWORD `
    -SqlProcessingPoolsUser "sa" `
    -SqlProcessingPoolsPassword $Env:SQL_SA_PASSWORD `
    -SqlReferenceDataUser "sa" `
    -SqlReferenceDataPassword $Env:SQL_SA_PASSWORD `
    -SqlMarketingAutomationUser "sa" `
    -SqlMarketingAutomationPassword $Env:SQL_SA_PASSWORD `    
    -SolrCorePrefix $Env:SOLR_CORE_PREFIX `
    -SolrURL $solrUrl `
    -Skip "CleanShards", "CreateShards", "CreateShardApplicationDatabaseServerLoginSqlCmd", "CreateShardManagerApplicationDatabaseUserSqlCmd", "CreateShard0ApplicationDatabaseUserSqlCmd", "CreateShard1ApplicationDatabaseUserSqlCmd", "ConfigureSolrSchemas"

RUN Remove-Item -Recurse -Force -Path c:\inetpub\wwwroot\xconnect\App_Data\logs

RUN Start-WebAppPool -Name $Env:SITE_NAME 
RUN Start-Website -Name $Env:SITE_NAME

# Fix models conflict for SC9 update 1: https://blog.ryanbailey.co.nz/2018/03/sitecore-experience-commerce-one-or.html
COPY xconnect/Sitecore.Commerce.Connect.XConnect.Models.json /Files/
RUN cp /Files/Sitecore.Commerce.Connect.XConnect.Models.json C:\inetpub\wwwroot\xconnect\App_data\jobs\continuous\IndexWorker\App_data\Models\; `
    cp /Files/Sitecore.Commerce.Connect.XConnect.Models.json C:\inetpub\wwwroot\xconnect\App_data\Models\

EXPOSE 443

ENTRYPOINT C:\ServiceMonitor.exe w3svc
