# escape=`
FROM microsoft/aspnet:4.7.1-windowsservercore-1709

SHELL ["powershell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop';"]

ARG HOST_NAME="SOLR"
ARG PORT=8983
ARG SERVICE_NAME="Solr-6"
ARG XCONNECT_CORE_PREFIX="xp0"
ARG SITECORE_CORE_PREFIX="xp0"
ARG CONFIG_PACKAGE="XP0 Configuration files rev.171002.zip"
ARG COMMERCE_SIF_PACKAGE="SIF.Sitecore.Commerce.1.0.1626.zip"

ENV SERVICE_NAME=${SERVICE_NAME}
ENV JAVA_HOME /Java/jre

# Download and install Java - Solr dependency
RUN Invoke-WebRequest -Method Get -Uri http://javadl.oracle.com/webapps/download/AutoDL?BundleId=210185 -OutFile /jreinstaller.exe ; `
    Start-Process -FilePath C:\jreinstaller.exe -PassThru -wait -ArgumentList "/s,INSTALLDIR=c:\Java\jre" ; `
    del C:\jreinstaller.exe

# Write variables to the master environment in the registry
RUN setx PATH '%PATH%;c:\\Java\\jre'

# Download and extract Solr project files
RUN Invoke-WebRequest -Method Get -Uri "http://mirrors.ukfast.co.uk/sites/ftp.apache.org/lucene/solr/6.6.2/solr-6.6.2.zip" -OutFile /solr.zip ; `
    Expand-Archive -Path /solr.zip -DestinationPath /solr ; `
    Remove-Item /solr.zip -Force

ADD files/$CONFIG_PACKAGE /Files/
ADD files/$COMMERCE_SIF_PACKAGE /Files/
ADD files/solr.pfx /Files/
ADD scripts /Scripts
ADD solr/Configure-SSL.ps1 /Scripts/

RUN C:\Scripts\Configure-SSL.ps1 -solrHost "$Env:HOST_NAME" -certPath c:\Files\solr.pfx

RUN $hostFileName = 'c:\\windows\\system32\\drivers\\etc\\hosts'; '\"`r`n127.0.0.1`t$Env:HOST_NAME\"' | Add-Content $hostFileName

RUN /Scripts/Install-SIF.ps1

WORKDIR "/solr/solr-6.6.2"

RUN Invoke-WebRequest -Method Get -Uri "https://nssm.cc/release/nssm-2.24.zip" -OutFile /nssm.zip ; `
    Expand-Archive -Path /nssm.zip -DestinationPath /nssm ; `
    Remove-Item /nssm.zip -Force

RUN /nssm/nssm-2.24/win64/nssm.exe install $Env:SERVICE_NAME "/solr/solr-6.6.2/bin/solr.cmd" "start" "-f" "-p $Env:PORT"
RUN /nssm/nssm-2.24/win64/nssm.exe set $Env:SERVICE_NAME AppEnvironmentExtra JAVA_HOME=C:\java\jre

RUN Expand-Archive -Path /Files/$Env:CONFIG_PACKAGE -DestinationPath /Files/Config 

RUN $solrUrl = 'https://{0}:{1}/solr' -f $Env:HOST_NAME, $Env:PORT; `
    Install-SitecoreConfiguration -Path "C:\\Files\\Config\\xconnect-solr.json" `
        -SolrUrl $solrUrl `
        -SolrRoot "c:\\solr\\solr-6.6.2" `
        -SolrService $Env:SERVICE_NAME `
        -CorePrefix $Env:XCONNECT_CORE_PREFIX

RUN $solrUrl = 'https://{0}:{1}/solr' -f $Env:HOST_NAME, $Env:PORT; `
    Install-SitecoreConfiguration -Path "C:\\Files\\Config\\sitecore-solr.json" `
        -SolrUrl $solrUrl `
        -SolrRoot "c:\\solr\\solr-6.6.2" `
        -SolrService $Env:SERVICE_NAME `
        -CorePrefix $Env:SITECORE_CORE_PREFIX

RUN Expand-Archive -Path /Files/$Env:COMMERCE_SIF_PACKAGE -DestinationPath /Files/CommerceSIF 

RUN $solrUrl = 'https://{0}:{1}/solr' -f $Env:HOST_NAME, $Env:PORT; `
    Install-SitecoreConfiguration -Path "C:\\Files\\CommerceSIF\\Configuration\\Commerce\\Solr\\sitecore-commerce-solr.json" `
        -SolrUrl $solrUrl `
        -SolrRoot "c:\\solr\\solr-6.6.2" `
        -SolrService $Env:SERVICE_NAME `
        -CorePrefix $Env:SITECORE_CORE_PREFIX `
        -SolrSchemas "C:\\Files\\CommerceSIF\\SolrSchemas"

EXPOSE 8983

HEALTHCHECK CMD powershell -command `
    try { `
        $solrUrl = 'https://{0}:{1}/solr' -f $Env:HOST_NAME, $Env:PORT; `
        $response = iwr $solrUrl -UseBasicParsing; `
        if ($response.StatusCode -eq 200) { return 0} else {return 1}; `
    } catch { return 1 }

ENTRYPOINT C:\ServiceMonitor.exe $Env:SERVICE_NAME
