# escape=`

# Stage 0: prepare files
ARG BASE_IMAGE
FROM ${BASE_IMAGE} AS prepare

ARG CONFIG_PACKAGE

SHELL ["powershell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop';"]

COPY files/$CONFIG_PACKAGE /Files/
COPY [ "xp/xconnect/custom-settings.json", "xp/xconnect/register-services.json", "xp/xconnect/Invoke-RegisterWindowsService.psm1", "/Files/Config/" ]

RUN Expand-Archive -Path /Files/$Env:CONFIG_PACKAGE -DestinationPath /Files/Config 


# Stage 1: create actual image
FROM ${BASE_IMAGE}

ARG SQL_SA_PASSWORD
ARG SQL_DB_PREFIX
ARG SQL_SERVER="mssql"
ARG SITE_NAME="xconnect"
ARG SOLR_CORE_PREFIX="xp0"
ARG SOLR_PORT="8983"
ARG XCONNECT_PACKAGE

SHELL ["powershell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop';"] 

COPY files/*.pfx /Files/
COPY files/$XCONNECT_PACKAGE /Files/
COPY dummylicense.xml /license/license.xml
COPY xp/xconnect/Boot.ps1 ./
COPY --from=prepare /Files/Config /Files/Config/
COPY xp/xconnect/custom-settings.json /Files/Config/
COPY scripts /Scripts

ENV XCONNECT_CLIENT_CERT_PATH="C:\\Files\\xconnect-client.pfx"
ENV XCONNECT_SSL_CERT_PATH="C:\\Files\\xconnect-ssl.pfx"
ENV SITE_NAME=${SITE_NAME}
ENV SIF_CONFIG="c:\\Files\\Config\\xconnect-xp0.json"

# Trust Self signed certificates & import XConnect certificate
RUN /Scripts/Import-Certificate.ps1 -certificateFile $Env:XCONNECT_SSL_CERT_PATH -secret 'secret' -storeName 'Root' -storeLocation 'LocalMachine'; `
    /Scripts/Import-Certificate.ps1 -certificateFile $Env:XCONNECT_SSL_CERT_PATH -secret 'secret' -storeName 'My' -storeLocation 'LocalMachine'; `
    /Scripts/Import-Certificate.ps1 -certificateFile $Env:XCONNECT_CLIENT_CERT_PATH -secret 'secret' -storeName 'Root' -storeLocation 'LocalMachine'; `
    /Scripts/Import-Certificate.ps1 -certificateFile $Env:XCONNECT_CLIENT_CERT_PATH -secret 'secret' -storeName 'My' -storeLocation 'LocalMachine'

RUN $config = Get-Content $Env:SIF_CONFIG | Where-Object { $_ -notmatch '^\s*\/\/'} | Out-String | ConvertFrom-Json; `
    $config.Tasks.InstallWDP.Params.Arguments | Add-Member -Name 'Skip' -Value @(@{'ObjectName' = 'dbDacFx'}, @{'ObjectName' = 'dbFullSql'}) -MemberType NoteProperty; `
    ConvertTo-Json $config -Depth 50 | Set-Content -Path $Env:SIF_CONFIG

RUN $solrUrl = 'http://solr:{0}/solr' -f $Env:SOLR_PORT; `
    Install-SitecoreConfiguration -Path $Env:SIF_CONFIG `
    -Package c:/Files/$Env:XCONNECT_PACKAGE `
    -LicenseFile "c:\\license\\license.xml" `
    -Sitename $Env:SITE_NAME `
    -XConnectCert "xConnect.client" `
    -SslCert "xconnect" `
    -SqlDbPrefix $Env:SQL_DB_PREFIX `
    -SqlServer $Env:SQL_SERVER `
    -SqlAdminUser "sa" `
    -SqlAdminPassword $Env:SQL_SA_PASSWORD `
    -SqlCollectionUser "sa" `
    -SqlCollectionPassword $Env:SQL_SA_PASSWORD `
    -SqlProcessingPoolsUser "sa" `
    -SqlProcessingPoolsPassword $Env:SQL_SA_PASSWORD `
    -SqlReferenceDataUser "sa" `
    -SqlReferenceDataPassword $Env:SQL_SA_PASSWORD `
    -SqlMessagingUser "sa" `
    -SqlMessagingPassword $Env:SQL_SA_PASSWORD `
    -SqlMarketingAutomationUser "sa" `
    -SqlMarketingAutomationPassword $Env:SQL_SA_PASSWORD `    
    -SolrCorePrefix $Env:SOLR_CORE_PREFIX `
    -SolrURL $solrUrl `
    -Skip "CleanShards", "CreateShards", "CreateShardApplicationDatabaseServerLoginSqlCmd", "CreateShardManagerApplicationDatabaseUserSqlCmd", `
        "CreateShard0ApplicationDatabaseUserSqlCmd", "CreateShard1ApplicationDatabaseUserSqlCmd", "ConfigureSolrSchemas", "StartServices", "InstallServices"; `
    Install-SitecoreConfiguration -Path 'c:/Files/Config/register-services.json' -Sitename $Env:SITE_NAME; `
    Install-SitecoreConfiguration -Path 'c:/Files/Config/custom-settings.json' -Sitename $Env:SITE_NAME; `
    Remove-Item -Recurse -Force -Path c:\inetpub\wwwroot\xconnect\App_Data\logs;

EXPOSE 443

ENTRYPOINT /Boot.ps1
